//==================================================
// This file contains the Excluded objects
// Generated By User: rfic
// Format Version: 2
// Date: Fri May 30 19:50:47 2025
// ExclMode: default
//==================================================

// Exclude DFT related logic
CHECKSUM: "690632875 733773157"
INSTANCE: async_fifo_test_top.dut.sync_rst_r
Toggle atpg_mode "net atpg_mode"

CHECKSUM: "690632875 2847915373"
INSTANCE: async_fifo_test_top.dut.sync_rst_r
Condition 1 "1249326504" "(atpg_mode ? rst_n : dff2) 1 -1"

CHECKSUM: "690632875 3287985690"
INSTANCE: async_fifo_test_top.dut.sync_rst_r
Branch 0 "330964210" "atpg_mode"

CHECKSUM: "690632875 733773157"
INSTANCE: async_fifo_test_top.dut.sync_rst_w
Toggle atpg_mode "net atpg_mode"

CHECKSUM: "690632875 2847915373"
INSTANCE: async_fifo_test_top.dut.sync_rst_w
Condition 1 "1249326504" "(atpg_mode ? rst_n : dff2) 1 -1"

CHECKSUM: "690632875 3287985690"
INSTANCE: async_fifo_test_top.dut.sync_rst_w
Branch 0 "330964210" "atpg_mode"

// Exclude RAL related assertions
CHECKSUM: "3615706772"
MODULE: uvm_pkg
Assert \uvm_reg_map::do_read .unnamed$$_0.unnamed$$_1 "assertion"
Assert \uvm_reg_map::do_write .unnamed$$_0.unnamed$$_1 "assertion"
