#-<-->-<-->-<-->-<-->-<-->-<-->-<-->-<-->-<-->-<-->-<-->-<-->-<-->-<-->-#
#									#
#		*** stuck at fault model ***				#
#		--> remove redundant faults generated by transition	#
#		--> scan_modes 3 basic_scan - 1 compression_scan 'TM4'	#
#		--> shift and capture using test clocks			#
#									#
#-<-->-<-->-<-->-<-->-<-->-<-->-<-->-<-->-<-->-<-->-<-->-<-->-<-->-<-->-#

source $env(SYNOPSYS_TMAX)/auxx/syn/tmax/tmax2pt.tcl
set top_design "async_fifo"
set occ_mode "pll_based"
set fault "stuck"
set test_modes [list TM1 TM2 TM3 TM4 ]

foreach mode $test_modes {
#------------------------------------------------------------------------
# 01 _ Read Design and Build the ATPG Design Model
#------------------------------------------------------------------------
source -e ./scripts/00_build.tcl

#------------------------------------------------------------------------
# 02 _ Read Test Protocol and set DRC constraints
#------------------------------------------------------------------------
set_drc ./dftc_protocols/${top_design}_${mode}.spf

# define pll clock as free running clock
add_clock 0 {wclk rclk} -refclock -shift

# avoid pattern simulation failure
set_drc -nodslave_remodel -noreclassify_invalid_dslaves

run_drc -patternexec ${mode}_occ_bypass

#------------------------------------------------------------------------
# 03 _ Control and Run ATPG
#------------------------------------------------------------------------
set_fault -model stuck  

if { $mode != "TM4" } {
	add_nofaults -module *COMPRESSOR*
}

add_faults -all

# remove redundant faults " detected by path delay model "
update_faults -direct_credit -external ./faults/${occ_mode}/${mode}/path_delay.flt
update_faults -direct_credit -external ./faults/${occ_mode}/${mode}/trans_sdd.flt
update_faults -direct_credit -external ./faults/${occ_mode}/${mode}/trans.flt

# run atpg engines
set_atpg -abort 100
run_atpg -auto basic_scan_only

set_atpg -capture_cycles 5
run_atpg -auto fast_sequential_only

set_atpg -full_seq_atpg
set_atpg -full_seq_time 0
set_atpg -full_seq_abort_limit 100
run_atpg -auto full_sequential_only

# write currents fault for later direct credit 
if {! [file exist ./faults/${occ_mode}/${mode}] } \
	{ exec mkdir -p ./faults/${occ_mode}/${mode} }
write_faults ./faults/${occ_mode}/${mode}/${fault}.flt -all -replace

#------------------------------------------------------------------------
# 04 _ Generate needed files " reports, images, patterns,testbenches "
#------------------------------------------------------------------------
source -e ./scripts/0F_capture_results.tcl

#------------------------------------------------------------------------
# 05 _ Report "Not Detected and ATPG Untestable" Faults
#------------------------------------------------------------------------
report_faults -class {nd au} -level 4 23 \
	>  ./reports/${occ_mode}/${fault}/${mode}/02_nd_au_faults.rpt
analyze_faults -class nd >>  ./reports/${occ_mode}/${fault}/${mode}/02_nd_au_faults.rpt
analyze_faults -class au >>  ./reports/${occ_mode}/${fault}/${mode}/02_nd_au_faults.rpt

#------------------------------------------------------------------------
# 06 _ Generate Test Timing Constraints for Pre-Simulation STA
#------------------------------------------------------------------------
if {! [file exist ./pt/constraints/${occ_mode}/${mode}]} \
	{exec mkdir -p ./pt/constraints/${occ_mode}/${mode} }
# Shifting Constraints
write_timing_constraints ./pt/constraints/${occ_mode}/${mode}/${top_design}_shift.sdc \
	-mode shift -replace -wft _default_WFT_
# Stuck-At Capture Constraints
write_timing_constraints ./pt/constraints/${occ_mode}/${mode}/${top_design}_stuck_capture.sdc \
	-mode capture -replace -wft _multiclock_capture_WFT_


build -force

}
exit
