#-<-->-<-->-<-->-<-->-<-->-<-->-<-->-<-->-<-->-<-->-<-->-<-->-<-->-<-->-#
#									#
#		*** path delay fault model ***				#
#		--> at speed testing for critical paths			#
#		--> critical paths generated by primetime		#
#		--> scan_modes 3 basic_scan - 1 compression_scan 'TM4'	#
#		--> shift and capture using test clocks			#
#									#
#-<-->-<-->-<-->-<-->-<-->-<-->-<-->-<-->-<-->-<-->-<-->-<-->-<-->-<-->-#

set top_design "async_fifo"
set occ_mode "occ_bypass"
set fault "path_delay"
set test_modes [list TM1 TM2 TM3 TM4]

foreach mode $test_modes {
#------------------------------------------------------------------------
# 01 _ Read Design and Build the ATPG Design Model
#------------------------------------------------------------------------
source -e ./scripts/00_build.tcl

#------------------------------------------------------------------------
# 02 _ Read Test Protocol and set DRC constraints
#------------------------------------------------------------------------
read_drc ./dftc_protocols/${top_design}_${mode}.spf

# edit for occ_bypass
update_wft -wft _allclock_capture_WFT_ -unit ns -strobe 1
update_clock -wft _allclock_launch_WFT_ \
	-clock [list ate_wclk ate_rclk] -pulse {97 99} -unit ns
update_clock -wft _allclock_capture_WFT_ \
	-clock ate_wclk -pulse {2 4} -unit ns
update_clock -wft _allclock_capture_WFT_ \
	-clock ate_rclk -pulse {4 6} -unit ns

# save and apply changes
if {! [file exist ./${occ_mode}_protocols]} \
	{ exec mkdir ./${occ_mode}_protocols}
if {[file exist ./${occ_mode}_protocols/${top_design}_${mode}.spf]} \
	{ exec rm -f ./${occ_mode}_protocols/${top_design}_${mode}.spf}

write_drc ./${occ_mode}_protocols/${top_design}_${mode}.spf

build -force
run_build_model $top_design

set_drc ./${occ_mode}_protocols/${top_design}_${mode}.spf

# read timing exceptions
read_sdc ./pt/constraints/${occ_mode}/${mode}/${top_design}_speed_capture.sdc

# constrain signals to certain values during capture
add_pi_constraints 1 {wrst_n rrst_n}
add_pi_constraints 0 test_se

add_pi_constraints 1 ren
add_pi_constraints 1 wen

add_pi_constraints 0 rptr_clr
add_pi_constraints 0 wptr_clr

# don't vary inputs and mask outputs during capture
set_delay -nopi_change
add_po_mask -all

# launch and capture with the same clock
set_delay -common_launch_capture

# avoid pattern simulation failure
set_drc -nodslave_remodel -noreclassify_invalid_dslaves

run_drc ./${occ_mode}_protocols/${top_design}_${mode}.spf  -patternexec ${mode}_${occ_mode}

#------------------------------------------------------------------------
# 03 _ Control and Run ATPG
#------------------------------------------------------------------------
set_fault -model path_delay  

# read critical paths generated by primetime
add_delay_path ./pt/crit_paths/${occ_mode}/${mode}/wclk-wclk_path.rep 
add_delay_path ./pt/crit_paths/${occ_mode}/${mode}/rclk-rclk_path.rep 

if { $mode != "TM4" } {
	add_nofaults -module *COMPRESSOR*
}

add_faults -all
run_atpg -auto

# write currents fault for later direct credit 
if {! [file exist ./faults/${occ_mode}/${mode}] } \
	{ exec mkdir -p ./faults/${occ_mode}/${mode} }
write_faults ./faults/${occ_mode}/${mode}/${fault}.flt -all -replace

#------------------------------------------------------------------------
# 04 _ Generate needed files " reports, images, patterns,testbenches "
#------------------------------------------------------------------------
source -e ./scripts/0F_capture_results.tcl




build -force

}
exit
